---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pleromam/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp bootstrap.min.css $DEPLOYPATH
    - /bin/cp main.css $DEPLOYPATH
    - /bin/cp main.js $DEPLOYPATH
    - /bin/cp mail.php $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH