---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp bootstrap.min.css $DEPLOYPATH
    - /bin/cp main.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH